version: "3"
services:
  api:
    build:
      context: .
      dockerfile: .docker/${APP_ENV:-development}.dockerfile
    ports:
      - 3001:3001
    env_file: .env/${APP_ENV:-development}.env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file: .env/${APP_ENV:-development}.env
